name: CI schedule test

on:
  workflow_dispatch:
  schedule:
    # - cron: "0 0 * * MON-FRI"
    - cron: "* * * * *"

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.workflow_run.head_branch || github.event.ref || github.ref }}"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  calculate-refs:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.calculate_branch.outputs.ref}}
      branch: ${{ steps.calculate_branch.outputs.branch}}
    steps:
      - name: Calculate Branch
        id: calculate_branch
        run: |
          if [[ ${{ github.event_name }} == 'workflow_run' ]]; then
            echo "ref=${{ github.event.workflow_run.head_commit.id }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name}} == 'workflow_dispatch' ]]; then
            echo "ref=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event_name }} == 'schedule' ]]; then
            echo "ref=${{ github.sha }}" >> $GITHUB_OUTPUT
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

  check-commit-count:
    needs: calculate-refs
    runs-on: ubuntu-latest
    outputs:
      has_commits: ${{ steps.calculate_commits.outputs.has_commits}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ needs.calculate-refs.outputs.branch }}

      - name: Check whether workflow should run
        id: calculate_commits
        continue-on-error: true
        run: |
          if [[ ${{ github.event_name }} == 'schedule']]; then
            if [[ $(git log --oneline --since '24 hours ago' | wc -l) -gt 0 ]]; then
              echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
            else
              echo "SHOULD_RUN=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
          fi

  build-jvm-image:
    needs: check-commit-count
    if: (github.repository == 'edeandrea/ci-test') && (contains(fromJSON('["workflow_dispatch", "schedule"]'), github.event_name) || ((github.event_name == 'worflow_run') && ((github.event.workflow_run.event == 'push') || (github.event.workflow_run.event == 'workflow_dispatch') && (github.event.workflow_run.conclusion == 'success') && (github.event.workflow_run.head_branch == 'main'))))
    runs-on: ubuntu-latest
    steps:
      - name: Print Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github)}}
        run: echo $GITHUB_CONTEXT

      - name: Print shouldRun
        run: echo "SHOULD_RUN = ${{ needs.check-commit-count.outputs.has_commits }}"

      # - name: Calculate Branch (workflow_run event)
      #   if: github.event_name == 'workflow_run'
      #   run: |
      #     echo "REF=${{ github.event.workflow_run.head_commit.id }}" >> $GITHUB_ENV
      #     echo "BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      # - name: Calculate Branch (workflow_dispatch event)
      #   if: github.event_name == 'workflow_dispatch'
      #   run: |
      #     echo "REF=${{ github.sha }}" >> $GITHUB_ENV
      #     echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      # - name: Calculate Branch (schedule event)
      #   if: github.event_name == 'schedule'
      #   run: |
      #     echo "REF=${{ github.sha }}" >> $GITHUB_ENV
      #     echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Print vars
        run: |
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.repository = ${{ github.repository }}"
          echo "REF = ${{ env.REF }}"
          echo "BRANCH = ${{ env.BRANCH }}"
          